import { Icon } from "../types/game";

export const allIcons: Icon[] = [
    {
        name: "Corazon",
        id: 1,
        image: "💝"
    },
    {
        name: "clip",
        id: 2,
        image: "📎"
    }, {
        name: "gato",
        id: 3,
        image: "🐈"
    }, {
        name: "calabaza",
        id: 4,
        image: "🎃"
    }, {
        name: "fuego",
        id: 5,
        image: "🔥"
    }, {
        name: "risa",
        id: 6,
        image: "😂"
    }, {
        name: "tren",
        id: 7,
        image: "🚂"
    }, {
        name: "payaso",
        id: 8,
        image: "🤡"//129313
    }, {
        name: "sandia",
        id: 9,
        image: "🍉"
    }, {
        name: "cerebro",
        id: 10,
        image: "🧠"
    }, {
        name: "bomba",
        id: 11,
        image: "💣"
    }, {
        name: "moto-amarilla",
        id: 12,
        image: "🛵"
    }, {
        name: "cuerpoespin",
        id: 13,
        image: "🦔"
    }, {
        name: "dinosaurio",
        id: 14,
        image: "🦕"
    }, {
        name: "lauchita",
        id: 15,
        image: "🦎"
    }, {
        name: "paleta",
        id: 16,
        image: "🍭"
    }, {
        name: "temperas",
        id: 17,
        image: "🎨"
    }, {
        name: "tortuga",
        id: 18,
        image: "🐢"
    }, {
        name: "pinochio",
        id: 19,
        image: "👺"
    }, {
        name: "ojitas",
        id: 20,
        image: "🌱"
    }, {
        name: "pinguino",
        id: 21,
        image: "🐧"
    }, {
        name: "paraguas",
        id: 22,
        image: "☔"
    }, {
        name: "velero",
        id: 23,
        image: "⛵"
    }, {
        name: "leon",
        id: 24,
        image: "🦁"
    }, {
        name: "arcoiris",
        id: 25,
        image: "🌈"
    }, {
        name: "ensalada",
        id: 26,
        image: "🥗"
    }, {
        name: "cebolla",
        id: 27,
        image: "🌰"
    }, {
        name: "pino",
        id: 28,
        image: "🌲"
    }, {
        name: "hongo",
        id: 29,
        image: "🍄"
    }, {
        name: "berenjena",
        id: 30,
        image: "🍆"
    }, {
        name: "cerezas",
        id: 31,
        image: "🍒"
    }, {
        name: "hamburguesa",
        id: 32,
        image: "🍔"
    }, {
        name: "pizza",
        id: 33,
        image: "🍕"
    }, {
        name: "papas-fritas",
        id: 34,
        image: "🍟"
    }, {
        name: "pepitos",
        id: 35,
        image: "🍪"
    }, {
        name: "moño",
        id: 36,
        image: "🎀"
    }, {
        name: "paquete",
        id: 37,
        image: "🎁"
    }, {
        name: "globo",
        id: 38,
        image: "🎈"
    }, {
        name: "sombrero-recibido",
        id: 39,
        image: "🎓"
    }, {
        name: "microfono",
        id: 30,
        image: "🎤"
    }, {
        name: "dardo",
        id: 41,
        image: "🎯"
    }, {
        name: "saxofon",
        id: 42,
        image: "🎷"
    }, {
        name: "pelota-de-basquet",
        id: 43,
        image: "🏀"
    }, {
        name: "pelota-de-rugby",
        id: 44,
        image: "🏈"
    }, {
        name: "pulpo",
        id: 45,
        image: "🐙"
    }, {
        name: "vaquita-de-san-antonio",
        id: 46,
        image: "🐞"
    }, {
        name: "pollito",
        id: 47,
        image: "🐣"
    }, {
        name: "rana",
        id: 48,
        image: "🐸"
    }, {
        name: "mounstro",
        id: 49,
        image: "👹"
    }, {
        name: "labios-pintados",
        id: 50,
        image: "💋"
    }, {
        name: "araña",
        id: 51,
        image: "🕷"
    }, {
        name: "coehte",
        id: 52,
        image: "🚀"
    }, {
        name: "palta",
        id: 53,
        image: "🥑"
    }, {
        name: "zanahoria",
        id: 54,
        image: "🥕"
    }, {
        name: "ensalada",
        id: 55,
        image: "🥙"
    }, {
        name: "brocoli",
        id: 56,
        image: "🥦"
    }, {
        name: "unicornio",
        id: 57,
        image: "🦄"
    }, {
        name: "langostintop",
        id: 58,
        image: "🦐"
    }
]



/*

verdes:
 pepino
 🥒
*/